Allow for descending date range.
rjsf-team/react-jsonschema-form pull request #1681
Opened 2020-03-31 07:37 UTC by jaycarey

### Reasons for making this change

Change to make the `yearsRange` option support descending values.

If this is related to existing tickets, include links to them as well.

### Checklist

* [x] **I'm updating documentation**
  - [x] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [x] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

2021-02-02 17:12 UTC, kaslav commented
Any chance there will be a progress on this? If not - should a new pull request be opened for the same feature?

2022-08-09 01:51 UTC, ahkhanjani requested changes
Is this change still valid? If so please fix the code and make a PR for rjsf-v5 branch.

2022-08-09 01:51 UTC, ahkhanjani commented on packages/core/src/components/widgets/AltDateWidget.js
> +  if (stop < 0) stop = new Date().getFullYear() + stop;
Please make this change:

```javascript
if (stop < 0) {
  stop = new Date().getFullYear() + stop;
}
```

2024-07-03 15:32 UTC, heath-freenome commented
Reimplemented this in https://github.com/rjsf-team/react-jsonschema-form/pull/4239, closing

2024-07-03 15:32 UTC, closed without merging