"examples" implementation for material-ui
rjsf-team/react-jsonschema-form pull request #2369
Opened 2021-05-07 23:02 UTC by inrumi

### Reasons for making this change

Related to the issue I raised heh 👉👈  #2368 

This wasn't really complicated, most of the heavy lifting was in the bootstrap implementation.

If test are required I can work on them this weekend.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### Deploy preview
![image](https://user-images.githubusercontent.com/18445985/117515647-76357900-af5c-11eb-904b-1d1e2e51b9c8.png)

Once CI finishes, you should be able to view a deploy preview of the playground from this PR at this link: https://deploy-preview-[PR_NUMBER]--rjsf.netlify.app/

2021-05-13 15:30 UTC, inrumi commented
@epicfaace is there any chance I can get a review here 🙏?

2021-05-13 19:26 UTC, epicfaace reviewed
Thanks for the PR -- it would be great to add tests (snapshot tests) if you're able.

2021-05-14 03:04 UTC, inrumi commented
> Thanks for the PR -- it would be great to add tests (snapshot tests) if you're able.

Done! :D

2021-05-25 14:51 UTC, inrumi commented
@epicfaace hi again! so I added the tests, everything is ok for this PR to be reviewed/merged?

2021-08-13 00:52 UTC, epicfaace approved these changes
Looks good, thanks!

2021-08-13 12:47 UTC, epicfaace requested changes
Can you also update snapshots by running `npm test -- -u`?

2021-08-13 12:47 UTC, epicfaace commented on packages/material-ui/src/TextWidget/TextWidget.tsx
> +          list: `examples_${id}`,
We shouldn't include this prop if `schema.examples` doesn't exist.

2022-01-04 15:51 UTC, Jame-Stitel commented
Please, we need this implementation... What needs to be done?

2022-09-07 00:43 UTC, heath-freenome commented
Fixed in v5 beta via refactor of this PR

2022-09-07 00:43 UTC, closed without merging