Fixing getMatchingOption
rjsf-team/react-jsonschema-form pull request #2676
Opened 2022-01-27 16:47 UTC by KittyJose

Fixing getMatchingOption in the case of oneOf/anyOf by validating schema only when formData is available

### Reasons for making this change

When there is a property with oneOf/anyOf - schema gets validated when there is not formData provided which leads to lot of load time. This fix will improves speed and performance.

2022-01-27 21:11 UTC, epicfaace requested changes

2022-01-27 21:11 UTC, epicfaace commented on packages/core/src/utils.js
> +      if (formData && isValid(augmentedSchema, formData, rootSchema)) {
Thanks. Can you add a test that covers this case, so it's clearer what issue this is fixing?

2022-02-01 14:29 UTC, KittyJose commented
@epicfaace , I have added a test to utils_test.js, in which I pass undefined as formData to getMatchingOption(), and it returns 0. My point is, if we dont pass formData to getMatchingOption => then there is no need to validate data against the whole schema.

In my schema, I use anyOfs (100 to 200 anyOfs) , and the check in utils.js passes undefined as formData as shown in the below pic. I also have a very large schema and multiple checks to validate formData against schema is very slow.

![image](https://user-images.githubusercontent.com/54106287/151984234-902d5c06-74e8-4805-b3fb-34b2ba771b41.png)

Maybe this is not the right solution, I can pass you my huge schema and you can paste it in playground and see it takes lot of time to load, eventually it loads after 3 minutes.

https://github.com/terminusdb/terminusdb-documents-ui/blob/main/seshatSchema.json

Any help would be really appreciated, we can set up a call as well, but do let me know what has to be done.

Thank you so much :)

2022-02-03 09:46 UTC, KittyJose commented
Ok, thanks @epicfaace, I shall join the call on discord this Friday 11 am ET  :)

2022-02-04 16:44 UTC, epicfaace commented on packages/core/src/utils.js
> +      if (formData && isValid(augmentedSchema, formData, rootSchema)) {
Change these in both places to `formData !== undefined`

2022-02-04 16:44 UTC, epicfaace commented on packages/core/src/utils.js
> +      if (formData && isValid(augmentedSchema, formData, rootSchema)) {
Add a comment

```
// For performance, skip validating subschemas if formData is undefined (as they would return false).
```

2022-02-04 16:50 UTC, epicfaace commented on packages/core/src/utils.js
> +      if (formData && isValid(augmentedSchema, formData, rootSchema)) {
At the beginning of the function -- let's add:

```
  // For performance, skip validating subschemas if formData is undefined. We just
  // want to get the first option in that case.
  if (formData === undefined) {
    return 0;
  }
```

2022-02-04 16:50 UTC, epicfaace commented on packages/core/src/utils.js
> +      if (formData && isValid(augmentedSchema, formData, rootSchema)) {
And remove the other changes in this file.

2022-02-04 16:50 UTC, epicfaace commented on packages/core/test/utils_test.js
> +    it("should infer correct anyOf schema based on data if passing undefined", () => {
Let's add a test for getMatchingOption
- where formData is `null`
- Where option 2 is `{type: null}`
- We expect `getMatchingOption` to be equal to 2



```
options = [{type: "string"}, {type: "string"}, {type: "null"}];
expect(getMatchingOption(null, options, rootSchema)).eql(2);
```

2022-02-11 15:03 UTC, epicfaace reviewed
Thanks! Can you fix the lint so the CI passes?

2022-02-14 18:14 UTC, KittyJose commented
@epicfaace ok I have fixed the lint issues :)

2022-02-16 03:54 UTC, epicfaace commented
Still failing -- see https://github.com/rjsf-team/react-jsonschema-form/runs/5189456113?check_suite_focus=true

2022-02-16 11:55 UTC, Dhakkain commented
I have a question about that - is it fix that issue too? #1564

2022-02-21 10:01 UTC, rrooij commented
The linter issues should be fixed. :smile:

2022-02-21 10:03 UTC, KittyJose commented
@epicfaace, Hello, Can you contact me on discord (Kitty Jose). I would like to discuss a matter with you. I cant seem to find ur username on discord.Thanks :D

2022-02-21 16:26 UTC, epicfaace commented
I'm not sure what your discord username is -- mine is Ashwin#0168.

2022-02-22 15:12 UTC, epicfaace approved these changes

2022-02-22 15:13 UTC, epicfaace requested changes
Can you update this branch with the latest from master and add an entry to CHANGELOG.md?

2022-02-25 15:44 UTC, rrooij commented
We added an entry to the changelog and rebased to master. :smile:

2022-02-25 15:45 UTC, epicfaace commented on CHANGELOG.md
> +- For performance, skip validating subschemas if formData is undefined (#2676)
```suggestion
- To improve performance, skip validating subschemas in oneOf / anyOf if formData is undefined (#2676)
```

2022-02-25 15:46 UTC, epicfaace approved these changes

2022-02-25 15:46 UTC, epicfaace commented on CHANGELOG.md
> +- For performance, skip validating subschemas if formData is undefined (#2676)
Can you make this change? I don't have access to edit. Thanks!

2022-02-28 08:53 UTC, rrooij commented
Did the change :+1:

2022-02-28 14:28 UTC, epicfaace approved these changes

2022-03-01 00:24 UTC, merged