Prevent the Playground from crashing on a form error.
rjsf-team/react-jsonschema-form pull request #3164
Opened 2022-09-30 15:56 UTC by nickgros

TODO: Need to come back to changelog and add each issue this will partially resolve

2022-09-30 21:26 UTC, heath-freenome requested changes

2022-09-30 21:26 UTC, heath-freenome commented on packages/playground/src/ErrorBoundary.jsx
> +  }
If you turn this into a fat-arrow function then you don't need the bind above


```suggestion
  resetErrorBoundary = () => {
    this.setState({ hasError: false, error: null });
  }
```

2022-09-30 21:26 UTC, heath-freenome commented on packages/playground/src/app.jsx
>  import localValidator from "@rjsf/validator-ajv6";
Reorder this so all external imports are first
```suggestion
import localValidator from "@rjsf/validator-ajv6";

import DemoFrame from "./DemoFrame";
```

2022-09-30 21:34 UTC, heath-freenome commented
@nickgros Have you verified that this will handle all the uses cases you've indicated will be fixed?

2022-10-03 14:19 UTC, nickgros commented on packages/playground/src/ErrorBoundary.jsx
> +    this.resetError = this.resetErrorBoundary.bind(this);
```suggestion
```

2022-10-03 16:03 UTC, heath-freenome approved these changes

2022-10-03 16:22 UTC, merged