Feature - (@rjsf/core) Reset form data, validations and errors
rjsf-team/react-jsonschema-form pull request #3492
Opened 2023-03-10 05:19 UTC by sarpere

### Reasons for making this change
Programmatically reset fields to default values and clear errors. 

Feature - #3459

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [x] **I'm adding a new feature**
  - [x] I've updated the playground with an example use of the feature

2023-03-10 16:19 UTC, heath-freenome requested changes

2023-03-11 02:12 UTC, sarpere commented on packages/core/test/Form.test.jsx
> +      child.reset();
Yeah, that's better way to work with react. I'll change all test cases.

2023-03-11 02:19 UTC, sarpere commented on packages/core/src/components/Form.tsx
> +      schemaValidationErrorSchema: errors.errorSchema,
I was thinking we could add some extra conditions for customization. Also, we can simplify it.

2023-03-11 02:26 UTC, sarpere commented on packages/core/src/components/Form.tsx
> +      schemaValidationErrorSchema: errors.errorSchema,
<img width="910" alt="Screenshot 2023-03-11 at 13 26 05" src="https://user-images.githubusercontent.com/29937197/224460173-5f8ecb1d-ef34-448e-8950-ac8e027e4fb5.png">

Do you have any suggestion for the typing error?

2023-03-11 02:29 UTC, sarpere commented on packages/core/src/components/Form.tsx
> +      schemaValidationErrorSchema: errors.errorSchema,
<img width="252" alt="Screenshot 2023-03-11 at 13 28 41" src="https://user-images.githubusercontent.com/29937197/224460287-b762360b-08c7-49c0-b91c-9e7c76847182.png">

I have faced with a typing error. I could do this for workaround.

2023-03-12 04:03 UTC, heath-freenome approved these changes

2023-03-12 05:20 UTC, heath-freenome commented
@sarpere Can you please update the `CHANGELOG.md` adding a header for 5.3.0, thanks!

2023-03-12 17:12 UTC, heath-freenome approved these changes

2023-03-12 17:33 UTC, merged