feat: pass down indexed title from array field
rjsf-team/react-jsonschema-form pull request #4002
Opened 2023-12-10 12:51 UTC by Rozamo

### Reasons for making this change

Fixes https://github.com/rjsf-team/react-jsonschema-form/issues/3983

## Changes
- Pass down indexed title from `ArrayField` to children
- Use the above `title` in `SchemaField`, `BooleanField` and `ObjectField` and `ArrayField`
- Add tests for the above changes

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [x] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [x] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

2023-12-11 17:31 UTC, heath-freenome requested changes
Can you please update the tests to validate these changes

2023-12-13 06:29 UTC, Rozamo commented on CHANGELOG.md
> +# 5.16.1
Done.

2023-12-13 06:30 UTC, Rozamo commented
> Can you please update the tests to validate these changes

Added tests for `ArrayField`. Let me know if tests at other places are also required.

2023-12-13 19:05 UTC, nickgros approved these changes

2023-12-13 23:47 UTC, nickgros commented
My only concern is that we're changing the displayed index from 0-based to 1-based. Should we consider that a breaking change?

2023-12-14 08:14 UTC, Rozamo commented
> My only concern is that we're changing the displayed index from 0-based to 1-based. Should we consider that a breaking change?

Very good point. Should I remove the `name` value from being used in the `fieldTitle` then? That way the if no title is provided in the array schema, the `name` with 0 based indexing would be used for the title as it was before. And if they provide the `title` they would get the 1 based indexed titles.

The only reason I used 1 based indexing for title was that I think they are mostly used for cosmetic purposes and it is more readable. If the dev is not providing the title it means that they might not require the readiblilty part.

2023-12-14 23:37 UTC, heath-freenome approved these changes

2023-12-14 23:38 UTC, heath-freenome commented
> > My only concern is that we're changing the displayed index from 0-based to 1-based. Should we consider that a breaking change?
> 
> Very good point. Should I remove the `name` value from being used in the `fieldTitle` then? That way the if no title is provided in the array schema, the `name` with 0 based indexing would be used for the title as it was before. And if they provide the `title` they would get the 1 based indexed titles.
> 
> The only reason I used 1 based indexing for title was that I think they are mostly used for cosmetic purposes and it is more readable. If the dev is not providing the title it means that they might not require the readiblilty part.

Yes, having title be 1 based only is not a breaking change

2023-12-14 23:38 UTC, merged