Feat: Allow raising errors from within a custom whatever(#2718)
rjsf-team/react-jsonschema-form pull request #4188
Opened 2024-05-09 00:31 UTC by abdalla-rko

### Reasons for making this change

I introduced a **raiseFieldErrors** method to raise errors from within a custom component(see #2718). 

The current behavior allows errors to be raised from custom components and when the form **onChange** is triggered, we clear the custom raised errors. I appreciate any feedback on this approach. If everything looks good, I'll write tests and implement this in other themes.

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

2024-05-10 19:24 UTC, heath-freenome commented
@abdalla-rko If the goal is to update the errorSchema via a custom widget, maybe it makes sense to update the `onChange` in `WidgetProps` to function similarly to the `onChange` in FieldProps, where the `errorSchema` can be updated as it is flows through the schema hierarchy. Feel free to join the next meeting so we can talk about it. Or reach out to me on Discord

2024-07-12 19:13 UTC, nickgros commented
@abdalla-rko are you still working on this?

2024-07-14 12:28 UTC, abdalla-rko commented
Hi @heath-freenome, Sorry for taking too long. I think the initial implementation is now like you suggested updating the **errorSchema** using **onChange** in the custom widget. Let me know if it's good and then I'll update the docs and other themes if needed.

2024-07-19 22:45 UTC, heath-freenome requested changes

2024-07-19 22:45 UTC, heath-freenome commented on packages/core/src/components/Form.tsx
> +        }
Use a local variable to reduce the operations slightly
```suggestion
        const errorAtKey = errors[errorKey];
        if (errorAtKey === undefined) {
          delete errors[errorKey];
        } else if (typeof errorAtKey === 'object' && !Array.isArray(errorAtKey.__errors)) {
          filterUndefinedErrors(errorAtKey);
        }
```

2024-07-19 22:45 UTC, heath-freenome commented on packages/core/src/components/Form.tsx
>      const pathSchema = schemaUtils.toPathSchema(retrievedSchema, '', formData);
Revert the space
```suggestion
    const retrievedSchema = schemaUtils.retrieveSchema(schema, formData);
    const pathSchema = schemaUtils.toPathSchema(retrievedSchema, '', formData);
```

2024-07-19 22:45 UTC, heath-freenome commented on packages/utils/src/types.ts
> +  onChange: (value: any, es?: ErrorSchema<T>, id?: string) => void;
I don't see any code that grabs these errors from the widget and passes it up the chain. If you added tests for this you should be able to validate that a custom widget that return an error schema and id get those errors shown.

2024-07-26 18:00 UTC, heath-freenome commented on packages/core/test/ObjectField.test.jsx
> +const ObjectFieldTest = (props) => {
Thanks for adding these... Can you also test with a custom Widget inside an object?

2024-07-26 18:00 UTC, heath-freenome commented on packages/core/test/StringField.test.jsx
> +const StringFieldTest = (props) => {
Thanks for adding these... Can you also test with a custom Widget inside an string field?

2024-07-27 18:01 UTC, heath-freenome reviewed
Almost there, just a couple of small things. Also, can you resolve the conflicts?

2024-07-29 17:17 UTC, heath-freenome commented on packages/core/src/components/Form.tsx
> +import { forEach } from 'lodash';
Oh shoot, sorry I missed this. Can you update the imports to explicitly import `forEach` like the ones above, putting it before `_get`

2024-07-31 20:10 UTC, heath-freenome commented on packages/core/src/components/Form.tsx
> +import _forEach from 'lodash/forEach';
```suggestion
import _forEach from 'lodash/forEach';
import _isEmpty from 'lodash/isEmpty';
import _pick from 'lodash/pick';
import _toPath from 'lodash/toPath';
```

2024-07-31 20:11 UTC, heath-freenome commented on packages/core/src/components/Form.tsx
> +import _forEach from 'lodash/forEach';
```suggestion
import _forEach from 'lodash/forEach';
import _get from 'lodash/get';
```

2024-08-02 19:15 UTC, heath-freenome commented on CHANGELOG.md
> +
```suggestion
## @rjsf/core 

- Support allowing raising errors from within a custom Widget [#2718](https://github.com/rjsf-team/react-jsonschema-form/issues/2718)

## @rjsf/utils

- Updated the `WidgetProps` type to add `es?: ErrorSchema<T>, id?: string` to the params of the `onChange` handler function

## Dev / docs / playground

-  Update the `custom-widget-fields.md` to add documentation for how to raise errors from a custom widget or field
```

2024-08-02 19:20 UTC, heath-freenome commented on CHANGELOG.md
> +-  Update the `custom-widget-fields.md` to add documentation for how to raise errors from a custom widget or field
```suggestion
-  Update the `custom-widget-fields.md` to add documentation for how to raise errors from a custom widget or field

```

2024-08-02 19:21 UTC, heath-freenome approved these changes

2024-08-03 23:27 UTC, merged