fix: formData change clear errorMessage
rjsf-team/react-jsonschema-form pull request #4429
Opened 2024-12-19 17:56 UTC by JinYuSha0

### Reasons for making this change

fixes #4426 

If this is related to existing tickets, include links to them as well. Use the syntax `fixes #[issue number]` (ex: `fixes #123`).

If your PR is non-trivial and you'd like to schedule a synchronous review, please add it to the weekly meeting agenda: https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit

### Checklist

- [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://rjsf-team.github.io/react-jsonschema-form/docs/contributing) of the Markdown text I've added
- [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests. I've run `npx nx run-many --target=build --exclude=@rjsf/docs && npm run test:update` to update snapshots, if needed.
  - [ ] I've updated [docs](https://rjsf-team.github.io/react-jsonschema-form/docs) if needed
  - [ ] I've updated the [changelog](https://github.com/rjsf-team/react-jsonschema-form/blob/main/CHANGELOG.md) with a description of the PR
- [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

2025-01-03 20:43 UTC, heath-freenome requested changes
@JinYuSha0 Please update the `CHANGELOG.md` to add a new `5.24.0` section since you are adding a new feature to `@rjsf/utils`. And make the few suggested changes. Also, provide 100% unit tests for the `getChangedFields()` function.

Also, these unit test, when written, should help you fix the test failures that exist in your PR.

2025-01-03 20:43 UTC, heath-freenome commented on packages/utils/src/getChangedFields.ts
> +export default function getChangedFields(a: any, b: any): string[] {
For better Typescript compatibility, `unknown` is preferred over `any`
```suggestion
export default function getChangedFields(a: unknown, b: unknown): string[] {
```

2025-01-03 20:43 UTC, heath-freenome commented on packages/utils/src/getChangedFields.ts
> + * @param {any} b - The second object, representing the updated data to compare.
```suggestion
 * @param a - The first object, representing the original data to compare.
 * @param b - The second object, representing the updated data to compare.
```

2025-01-05 15:47 UTC, JinYuSha0 commented on packages/utils/src/getChangedFields.ts
> + * @param {any} b - The second object, representing the updated data to compare.
ok, I will try to do this

2025-01-06 17:43 UTC, heath-freenome commented
@JinYuSha0 I just merged another fix to the method you are changing... Can you first check to see if that fix also fixes the issue you are attempting to fix with this PR? Thanks. If not, then rebase that change into your PR first.

2025-01-06 20:40 UTC, JinYuSha0 commented on packages/utils/src/getChangedFields.ts
> + * @param {any} b - The second object, representing the updated data to compare.
```
git log --oneline
f5a24b25 (HEAD -> main, origin/main, origin/HEAD) Bug: schema with conditions where switching to then/else subschemas did not reflect the actual validation errors in the onChange event. (#4432)
c2a60d44 Bug: Issue with formData not updating when dependencies change (#4388)
```
![rjsf-issuse4](https://github.com/user-attachments/assets/d8686248-fe87-40f2-8a0a-8cc3fded94e4)

It seems that this problem has not been solved, thank you very much for your attention to this issue. I hope this project will get better and better.

2025-01-06 20:43 UTC, JinYuSha0 commented
@heath-freenome 

![rjsf-issuse4](https://github.com/user-attachments/assets/d8686248-fe87-40f2-8a0a-8cc3fded94e4)

I pulled the latest commit in the main branch and executed build, it seems that this problem has not been solved, thank you very much for your attention to this issue.

```
git log --oneline
f5a24b25 (HEAD -> main, origin/main, origin/HEAD) Bug: schema with conditions where switching to then/else subschemas did not reflect the actual validation errors in the onChange event. (#4432)
c2a60d44 Bug: Issue with formData not updating when dependencies change (#4388)
```

2025-01-07 17:17 UTC, heath-freenome commented
Also, it looks like your changes are breaking a `core` test. Can you investigate and fix?

2025-01-08 17:24 UTC, JinYuSha0 commented
I fix the breaking `core` test

1. change formData then error should be disappears.
2. when formData is srting, deepEquals again

2025-01-09 18:05 UTC, heath-freenome approved these changes

2025-01-09 18:05 UTC, merged